from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch


class PDFGenerator:

    def generate_report(self, data, filename):

        document = SimpleDocTemplate(filename)

        styles = getSampleStyleSheet()

        title_style = styles["Title"]
        title_style.alignment = TA_CENTER

        heading_style = styles["Heading1"]

        normal_style = styles["BodyText"]

        elements = []

        # ----------------------------------------
        # Cover Page
        # ----------------------------------------

        elements.append(
            Paragraph(
                "GitHub Repository Analysis Report",
                title_style
            )
        )

        elements.append(Spacer(1, 0.4 * inch))

        elements.append(
            Paragraph(
                "Generated by GitHub Repository Analyzer with AI Assistant",
                normal_style
            )
        )

        elements.append(Spacer(1, 0.6 * inch))

        # ----------------------------------------
        # Repository Overview
        # ----------------------------------------

        elements.append(
            Paragraph(
                "Repository Overview",
                heading_style
            )
        )

        elements.append(Spacer(1, 0.2 * inch))

        table_data = [

            ["Repository Name", data["repository_name"]],

            ["Default Branch", data["default_branch"]],

            ["Branches", data["total_branches"]],

            ["Commits", data["total_commits"]],

            ["Contributors", data["total_contributors"]]

        ]

        table = Table(
            table_data,
            colWidths=[180, 250]
        )

        table.setStyle(

            TableStyle([

                ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.grey),

                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold")

            ])

        )

        elements.append(table)

        elements.append(Spacer(1, 0.5 * inch))
        # ----------------------------------------
        # Repository Statistics
        # ----------------------------------------

        elements.append(
            Paragraph(
                "Repository Statistics",
                heading_style
            )
        )

        elements.append(Spacer(1, 0.2 * inch))

        statistics_table = [

            ["Statistic", "Value"],

            ["Total Files", data["statistics"]["total_files"]],

            ["Total Directories", data["statistics"]["total_directories"]]

        ]

        table = Table(
            statistics_table,
            colWidths=[220, 180]
        )

        table.setStyle(

            TableStyle([

                ("BACKGROUND", (0, 0), (-1, 0), colors.darkgreen),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.grey),

                ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold")

            ])

        )

        elements.append(table)

        elements.append(Spacer(1, 0.4 * inch))

        # ----------------------------------------
        # Programming Languages
        # ----------------------------------------

        elements.append(
            Paragraph(
                "Programming Languages",
                heading_style
            )
        )

        elements.append(Spacer(1, 0.2 * inch))

        language_data = [
            ["Language", "Files", "Percentage"]
        ]

        languages = data["languages"]

        total = sum(languages.values())

        for language, count in languages.items():

            percentage = (count / total) * 100

            language_data.append([
                language,
                str(count),
                f"{percentage:.1f}%"
            ])

        language_table = Table(
            language_data,
            colWidths=[180, 100, 120]
        )

        language_table.setStyle(

            TableStyle([

                ("BACKGROUND", (0, 0), (-1, 0), colors.navy),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.grey),

                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold")

            ])

        )

        elements.append(language_table)

        elements.append(Spacer(1, 0.4 * inch))
        # ----------------------------------------
        # Dependencies
        # ----------------------------------------

        elements.append(
            Paragraph(
                "Dependencies",
                heading_style
            )
        )

        elements.append(Spacer(1, 0.2 * inch))

        dependency_data = [
            ["Dependency"]
        ]

        dependencies = data["dependencies"]

        if dependencies:

            for dependency in dependencies:
                dependency_data.append([dependency])

        else:

            dependency_data.append(["No dependencies found"])

        dependency_table = Table(
            dependency_data,
            colWidths=[350]
        )

        dependency_table.setStyle(

            TableStyle([

                ("BACKGROUND", (0, 0), (-1, 0), colors.darkgreen),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.grey),

                ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold")

            ])

        )

        elements.append(dependency_table)

        elements.append(Spacer(1, 0.4 * inch))
        # ----------------------------------------
        # Hotspot Files
        # ----------------------------------------

        elements.append(
            Paragraph(
                "Hotspot Files",
                heading_style
            )
        )

        elements.append(Spacer(1, 0.2 * inch))

        hotspot_data = [
            ["File", "Commits"]
        ]

        hotspot_files = data["hotspot_files"]

        if hotspot_files:

            for file_name, commits in hotspot_files:

                hotspot_data.append([
                    file_name,
                    str(commits)
                ])

        else:

            hotspot_data.append([
                "No hotspot files found",
                "-"
            ])

        hotspot_table = Table(
            hotspot_data,
            colWidths=[320, 80]
        )

        hotspot_table.setStyle(

            TableStyle([

                ("BACKGROUND", (0, 0), (-1, 0), colors.darkred),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.grey),

                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold")

            ])

        )

        elements.append(hotspot_table)

        elements.append(Spacer(1, 0.4 * inch))
        # ----------------------------------------
        # AI Summary
        # ----------------------------------------

        elements.append(
            Paragraph(
                "AI Repository Summary",
                heading_style
            )
        )

        elements.append(Spacer(1, 0.2 * inch))

        summary = data["ai_summary"]

        summary_paragraph = Paragraph(
            summary.replace("\n", "<br/>"),
            normal_style
        )

        elements.append(summary_paragraph)

        elements.append(Spacer(1, 0.4 * inch))
        # ----------------------------------------
        # AI Recommendations
        # ----------------------------------------

        elements.append(
            Paragraph(
                "AI Recommendations",
                heading_style
            )
        )

        elements.append(Spacer(1, 0.2 * inch))

        recommendations = data["ai_recommendations"]

        recommendation_paragraph = Paragraph(
            recommendations.replace("\n", "<br/>"),
            normal_style
        )

        elements.append(recommendation_paragraph)

        elements.append(Spacer(1, 0.4 * inch))
        document.build(elements)