from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image
)
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import os
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch


class PDFGenerator:
    def create_language_chart(self, languages):

        labels = list(languages.keys())
        sizes = list(languages.values())

        plt.figure(figsize=(5, 5))

        plt.pie(
            sizes,
            labels=labels,
            autopct="%1.1f%%",
            startangle=140
        )

        plt.title("Programming Languages")

        chart_path = "language_chart.png"

        plt.savefig(chart_path, bbox_inches="tight")

        plt.close()

        return chart_path
    def generate_report(self, data, filename):

        document = SimpleDocTemplate(filename)

        styles = getSampleStyleSheet()

        title_style = styles["Title"]
        title_style.alignment = TA_CENTER

        heading_style = styles["Heading1"]

        normal_style = styles["BodyText"]

        elements = []

        # ----------------------------------------
        # Cover Page
        # ----------------------------------------

        elements.append(
            Paragraph(
                "GitHub Repository Analysis Report",
                title_style
            )
        )

        elements.append(Spacer(1, 0.4 * inch))

        elements.append(
            Paragraph(
                "Generated by GitHub Repository Analyzer with AI Assistant",
                normal_style
            )
        )

        elements.append(Spacer(1, 0.6 * inch))

        # ----------------------------------------
        # Repository Overview
        # ----------------------------------------

        elements.append(
            Paragraph(
                "Repository Overview",
                heading_style
            )
        )

        elements.append(Spacer(1, 0.2 * inch))

        table_data = [

            ["Repository Name", data["repository_name"]],

            ["Default Branch", data["default_branch"]],

            ["Branches", data["total_branches"]],

            ["Commits", data["total_commits"]],

            ["Contributors", data["total_contributors"]]

        ]

        table = Table(
            table_data,
            colWidths=[180, 250]
        )

        table.setStyle(

            TableStyle([

                ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.grey),

                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold")

            ])

        )

        elements.append(table)

        elements.append(Spacer(1, 0.5 * inch))
        # ----------------------------------------
        # Repository Statistics
        # ----------------------------------------

        elements.append(
            Paragraph(
                "Repository Statistics",
                heading_style
            )
        )

        elements.append(Spacer(1, 0.2 * inch))

        statistics_table = [

            ["Statistic", "Value"],

            ["Total Files", data["statistics"]["total_files"]],

            ["Total Directories", data["statistics"]["total_directories"]]

        ]

        table = Table(
            statistics_table,
            colWidths=[220, 180]
        )

        table.setStyle(

            TableStyle([

                ("BACKGROUND", (0, 0), (-1, 0), colors.darkgreen),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.grey),

                ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold")

            ])

        )

        elements.append(table)

        elements.append(Spacer(1, 0.4 * inch))

        # ----------------------------------------
        # Programming Languages
        # ----------------------------------------

        elements.append(
            Paragraph(
                "Programming Languages",
                heading_style
            )
        )

        elements.append(Spacer(1, 0.2 * inch))

        language_data = [
            ["Language", "Files", "Percentage"]
        ]

        languages = data["languages"]

        total = sum(languages.values())

        for language, count in languages.items():

            percentage = (count / total) * 100

            language_data.append([
                language,
                str(count),
                f"{percentage:.1f}%"
            ])

        language_table = Table(
            language_data,
            colWidths=[180, 100, 120]
        )

        language_table.setStyle(

            TableStyle([

                ("BACKGROUND", (0, 0), (-1, 0), colors.navy),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.grey),

                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold")

            ])

        )

        elements.append(language_table)
        # ----------------------------------------
        # Language Pie Chart
        # ----------------------------------------

        chart_path = self.create_language_chart(data["languages"])

        elements.append(Spacer(1, 0.2 * inch))

        elements.append(
            Image(
                chart_path,
                width=250,
                height=250
            )
        )

        elements.append(Spacer(1, 0.4 * inch))

        elements.append(Spacer(1, 0.4 * inch))
        # ----------------------------------------
        # Dependencies
        # ----------------------------------------

        elements.append(
            Paragraph(
                "Dependencies",
                heading_style
            )
        )

        elements.append(Spacer(1, 0.2 * inch))

        dependency_data = [
            ["Dependency"]
        ]

        dependencies = data["dependencies"]

        if dependencies:

            for dependency in dependencies:
                dependency_data.append([dependency])

        else:

            dependency_data.append(["No dependencies found"])

        dependency_table = Table(
            dependency_data,
            colWidths=[350]
        )

        dependency_table.setStyle(

            TableStyle([

                ("BACKGROUND", (0, 0), (-1, 0), colors.darkgreen),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.grey),

                ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold")

            ])

        )

        elements.append(dependency_table)

        elements.append(Spacer(1, 0.4 * inch))
        # ----------------------------------------
        # Hotspot Files
        # ----------------------------------------

        elements.append(
            Paragraph(
                "Hotspot Files",
                heading_style
            )
        )

        elements.append(Spacer(1, 0.2 * inch))

        hotspot_data = [
            ["File", "Commits"]
        ]

        hotspot_files = data["hotspot_files"]

        if hotspot_files:

            for file_name, commits in hotspot_files:

                hotspot_data.append([
                    file_name,
                    str(commits)
                ])

        else:

            hotspot_data.append([
                "No hotspot files found",
                "-"
            ])

        hotspot_table = Table(
            hotspot_data,
            colWidths=[320, 80]
        )

        hotspot_table.setStyle(

            TableStyle([

                ("BACKGROUND", (0, 0), (-1, 0), colors.darkred),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.grey),

                ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

                ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold")

            ])

        )

        elements.append(hotspot_table)
        # ----------------------------------------
        # Hotspot Files Chart
        # ----------------------------------------

        chart_path = self.create_hotspot_chart(
            data["hotspot_files"]
        )

        elements.append(Spacer(1, 0.2 * inch))

        elements.append(
            Image(
                chart_path,
                width=420,
                height=260
            )
        )
        elements.append(Spacer(1, 0.4 * inch))
        # ----------------------------------------
        # AI Summary
        # ----------------------------------------

        elements.append(
            Paragraph(
                "AI Repository Summary",
                heading_style
            )
        )

        elements.append(Spacer(1, 0.2 * inch))

        summary = data["ai_summary"]

        # Repository Purpose
        elements.append(Paragraph("<b>Repository Purpose</b>", normal_style))
        elements.append(Paragraph(summary["repository_purpose"], normal_style))
        elements.append(Spacer(1, 0.15 * inch))

        # Technologies Used
        elements.append(Paragraph("<b>Technologies Used</b>", normal_style))

        for tech in summary["technologies_used"]:
            elements.append(Paragraph(f"• {tech}", normal_style))

        elements.append(Spacer(1, 0.15 * inch))

        # Project Organization
        elements.append(Paragraph("<b>Project Organization</b>", normal_style))
        elements.append(Paragraph(summary["project_organization"], normal_style))
        elements.append(Spacer(1, 0.15 * inch))

        # Intended Users
        elements.append(Paragraph("<b>Intended Users</b>", normal_style))
        elements.append(Paragraph(summary["intended_users"], normal_style))
        elements.append(Spacer(1, 0.15 * inch))

        # Beginner Summary
        elements.append(Paragraph("<b>Beginner Summary</b>", normal_style))
        elements.append(Paragraph(summary["beginner_summary"], normal_style))
        elements.append(Spacer(1, 0.4 * inch))
        # ----------------------------------------
        # AI Recommendations
        # ----------------------------------------

        elements.append(
            Paragraph(
                "AI Recommendations",
                heading_style
            )
        )

        elements.append(Spacer(1, 0.2 * inch))

        recommendations = data["ai_recommendations"]

        # Repository Strengths
        elements.append(Paragraph("<b>Repository Strengths</b>", normal_style))

        for strength in recommendations["strengths"]:
            elements.append(Paragraph(f"✔ {strength}", normal_style))

        elements.append(Spacer(1, 0.15 * inch))

        # Areas for Improvement
        elements.append(Paragraph("<b>Areas for Improvement</b>", normal_style))

        for improvement in recommendations["areas_for_improvement"]:
            elements.append(Paragraph(f"• {improvement}", normal_style))

        elements.append(Spacer(1, 0.15 * inch))

        # Best Practices
        elements.append(Paragraph("<b>Best Practices</b>", normal_style))

        for practice in recommendations["best_practices"]:
            elements.append(Paragraph(f"• {practice}", normal_style))

        elements.append(Spacer(1, 0.15 * inch))

        # Overall Quality
        elements.append(Paragraph("<b>Overall Repository Quality</b>", normal_style))
        elements.append(
            Paragraph(
                recommendations["overall_quality"],
                normal_style
            )
        )

        elements.append(Spacer(1, 0.4 * inch))
        document.build(elements)
    def create_hotspot_chart(self, hotspot_files):

        files = [item[0] for item in hotspot_files[:10]]
        commits = [item[1] for item in hotspot_files[:10]]

        plt.figure(figsize=(8, 5))

        plt.barh(files, commits)

        plt.title("Top 10 Hotspot Files")

        plt.xlabel("Number of Commits")

        plt.tight_layout()

        chart_path = "hotspot_chart.png"

        plt.savefig(chart_path, bbox_inches="tight")

        plt.close()

        return chart_path